name: quizgame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.2
  provider: ^6.0.5
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - .env
